site_name: !ENV [SITE_NAME, 'Millennium Machines']
site_url: !ENV [SITE_URL, 'https://millenniummachines.github.io/docs']
site_description: !ENV [SITE_DESCRIPTION, 'Documentation for Millennium Machines']
repo_url: https://github.com/MillenniumMachines/millenniummachines.github.io
edit_uri: !ENV [EDIT_URL, 'edit/main/docs/']

nav:
  - Home: index.md
  - "Milo - Desktop CNC Mill":
    - Sourcing Guide: milo/bom/sourcing_guide.md
    - Printing Guide: milo/printing/print_guide.md
    - Frequently Asked Questions: milo/faq.md
    - Assembly Manual:
        - Acknowledgements: milo/manual/chapters/10_acknowledgements.md
        - Introduction: milo/manual/chapters/20_introduction.md
        - Hardware Reference: milo/manual/chapters/30_hardware_reference.md
        - Y-Axis Assembly: milo/manual/chapters/40_y_axis_assembly.md
        - X-Axis Assembly: milo/manual/chapters/50_x_axis_assembly.md
        - Z-Axis Assembly: milo/manual/chapters/60_z_axis_assembly.md
        - FMJ Assembly: milo/manual/chapters/70_fmj_assembly.md
        - Table Assembly: milo/manual/chapters/80_table_assembly.md
        - Install RRF: milo/manual/chapters/90_install_rrf.md
        - Assemble Electronics: milo/manual/chapters/100_assemble_electronics.md
        - Pre-Flight Checks: milo/manual/chapters/110_pre_flight_checks.md

  - "Long John Toolsetter":
    - Sourcing and Print Guild: long-john/bom/sourcing_and_print_guide.md
    - Assembly Manual: long-john/manual/assembly_manual.md
    - Electronics Manual: long-john/manual/manual.md
  - MillenniumOS:
    - Installation: millennium-os/manual/installation.md
    - Usage: millennium-os/manual/usage.md
  - "Contact Us": contact-us.md

extra:
  SITE_INTRO: !ENV
    - SITE_INTRO
    - |
      Welcome to the Millennium Machines documentation site.
      Here you can find guides on how to source, build,
      and maintain your own **Millennium Machine**!

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - macros

theme:
  name: material
  font:
    text: Roboto
  logo: img/millennium-machines-icon.png
  icon:
    logo: fontawesome/solid/industry
    annotation: material/wrench-outline
  favicon: img/millennium-machines-icon.png
  palette:
    scheme: slate
    primary: red
    accent: custom

  features:
    - content.code.annotate
    - content.action.edit
    - navigation.tracking

markdown_extensions:
  - abbr
  - attr_list
  - md_in_html
  - admonition
  - footnotes
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
